### ISSUE TITLE
TextField component displays the letter "Å" as "A"

### ISSUE THREAD

**Issue by lemsa** [equinor/design-system#2467] opened 2022-09-06 10:26 UTC
**The letter Å is displayed as an "A" in the TextField component**

**Steps to reproduce the bug**

1. Open https://eds-storybook-react.azurewebsites.net/?path=/docs/inputs-textfield--introduction
2. Go into the first TextField component there and write "Å". It is displayed as an "A". Overriding the font-family to something else than "Equinor" makes it display as an "Å", so the letter itself is correct, but the display is not.

**Expected behavior**

The letter "Å" and not "A" should be displayed.

**Specifications**

- Version: 104
- Browser: Chrome 
- OS: Windows 10 Enterprise

**Comment by mimarz** [comment] 2022-09-06 10:31
Hey! Thanks for reporting. 

Do you have a screenshot to show us? 
Can't seem to reproduce the bug. On a mac though 🤔

**Comment by lemsa** [comment] 2022-09-06 10:34
![image](https://user-images.githubusercontent.com/35260806/188613953-ea75e5b7-6dc4-4369-abbb-bc1949e96da3.png)

**Comment by lemsa** [comment] 2022-09-06 10:38
BTW - the letters: "å, Æ, æ, Ø, ø" are all okay. The only issues is with the letter "Å".

**Comment by mimarz** [comment] 2022-09-06 10:42
Looks like this here: 
![image](https://user-images.githubusercontent.com/1070981/188615284-550d7239-2b7e-4357-87ac-3586a93c31d5.png)

Would you have time for a call later to show us?

**Comment by lemsa** [comment] 2022-09-06 10:43
Sure - I am in Equinor Teams.

**Comment by mimarz** [comment] 2022-09-06 10:51
> Sure - I am in Equinor Teams.

Super! We set up a meeting at 14.00 with me and @vnys to have a look at this peculiar bug 🐛🤔

**Comment by mimarz** [comment] 2022-09-06 10:55
Notes from DMs on Slack
* Equinor managed windows laptop
* 2560x1440 resolution

**Comment by lemsa** [comment] 2022-09-06 12:15
If I override the line-height in Developer tools in the textinput field from 1.5em to 2.25em, then the Å is displayed correctly. 

However 1.5em is what we want...

**Comment by mimarz** [comment] 2022-09-06 13:31
After our meeting and testing using Equinor Citrix, it turns out that there is something with Equinor managed computers that disturbs the `line-height` and somehow clamps its. We were not able to find out the cause of this. Maybe it has something to do with the pre-installed font that come with Equinor managed computers.

We did find out that removing the fixed height on `input` resolved this line-height issue. This change has however already been done in our re-write of "inputs" with epic #2336 .

One important take away from this issue is that we need to also test our components via the Equinor Citrix.

Closing issue as it will be resolved when #2336 is released.

**Closed by mimarz** 2022-09-06 13:31 UTC
Labels: 🐛 bug, react
