### ISSUE TITLE
Menu - focus always on last MenuItem

### ISSUE THREAD

**Issue by skrulling** [equinor/design-system#2659] opened 2022-11-16 12:36 UTC
**Describe the bug**

When using the Menu component and having more than one MenuItem. If one clicks a MenuItem, the last one will always get focus before the Menu closes. The onClick function on MenuItem seems unaffected

![image](https://user-images.githubusercontent.com/17255103/202182554-29b62bc0-3f9d-490a-ad8c-6bcba01133e9.png)

Sidenote: Using the arrows to navigate MenuItems also does not work in this scenario

**Steps to reproduce the bug**

1. Make a Menu with more than one MenuItem
2. Wrap the MenuItem in another component
3. Click the first MenuItem and watch the last MenuItem biefly get focus

**Expected behavior**

Would expect the clicked MenuItem to get focus

**Specifications**

- Version: 0.24.0
- Browser: Chrome
- OS: Windows

**Additional context**

![image](https://user-images.githubusercontent.com/17255103/202181766-d233474d-34d4-471d-a202-0dafa99835e0.png)

MenuWindow == Menu
![image](https://user-images.githubusercontent.com/17255103/202181936-3ccc54f1-a3be-405b-865a-c88c68068227.png)

MenuItemStyled == MenuItem
![image](https://user-images.githubusercontent.com/17255103/202182052-6f3901f1-83c2-43a1-b640-d39b892b2788.png)

In code for copy pasting
`<AccordionContextMenu label="dashboard">
            <AccordionContextMenuItem
              doChange={() => console.log("TODO")}
              icon={add_circle_outlined}
              label={"Add table"}
            />
            <AccordionContextMenuItem
              doChange={() => setEditName(true)}
              icon={edit_text}
              label={"Rename dashboard"}
            />
            <AccordionContextMenuItem
              doChange={() => console.log("TODO")}
              icon={delete_to_trash}
              label={"Delete dashboard"}
            />
          </AccordionContextMenu>`

`interface AccordionContextMenuProps {
  label: string;
  children: JSX.Element | JSX.Element[];
}

const AccordionContextMenu = ({
  label,
  children,
}: AccordionContextMenuProps): JSX.Element => {
  const [isOpen, setIsOpen] = useState<boolean>(false);
  const ref = useRef<HTMLButtonElement>(null);

  const openMenu = (): void => {
    setIsOpen(true);
  };
  const closeMenu = (): void => {
    setIsOpen(false);
  };

  return (
    <>
      <Button
        ref={ref}
        id={`${label}-menu`}
        aria-haspopup="true"
        aria-expanded={isOpen}
        aria-controls={`${label}-menu-window`}
        onClick={(event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
          isOpen ? closeMenu() : openMenu();
          event.stopPropagation();
        }}
        variant="ghost_icon"
      >
        <Icon data={more_vertical} />
      </Button>
      <MenuWindow
        open={isOpen}
        id={`${label}-menu-window`}
        aria-labelledby={`${label}-menu`}
        onClose={closeMenu}
        anchorEl={ref.current}
        placement="bottom-end"
      >
        {children}
      </MenuWindow>
    </>
  );
};

export default AccordionContextMenu;
`
`interface AccordionContextMenuItemProps {
  doChange: () => void,
  label: string,
  icon: IconData,
}

const AccordionContextMenuItem = ({
  doChange, label, icon
}: AccordionContextMenuItemProps): JSX.Element => {

  return (
    <MenuItemStyled
      onClick={() => doChange()}
    >
      <Icon data={icon} color={textIconDefault} />
      <Typography
        group="navigation"
        variant="menu_title"
        as="span"
        color={textIconDefault}
      >
        {label}
      </Typography>
    </MenuItemStyled>
  );
};

export default AccordionContextMenuItem;
`

**Comment by oddvernes** [comment] 2022-11-22 12:55
Alright I've had a look at this. 
The problem is our logic inside `Menu` to determine indexable children for keyboard navigation expects `item.type === MenuItem` but what it recieves is an `AccordionContextMenuItem` with icon and label etc so it fails alredy at that point. but even if i remove that check it still doesn't work 🤷‍♂️. 
I did find a workaround however, if you can set additional styles with `className` or `style` because this will not work with `Styled(Menu.Item)`. 
If you make `AccordionContextMenuItem` a generic div to pass the props to:
![bilde](https://user-images.githubusercontent.com/4499531/203317351-dd0b8385-858b-4e8b-a69f-7a2495e6192c.png)
Then in `AccordionContextMenu` you map the props to Menu.Item there: 
![bilde](https://user-images.githubusercontent.com/4499531/203318027-1aa89dd9-b78e-4995-8295-c9c553f78fce.png)
and then pass on newChildren insted of children. I don't know if there is a better solution but at least this seems to work 😅 

code: 
```  
interface AccordionContextMenuItemProps
    extends React.HTMLAttributes<HTMLDivElement> {
    doChange: () => void
    label: string
    icon: IconData
  }

  const AccordionContextMenuItem = (
    props: AccordionContextMenuItemProps,
  ): JSX.Element => {
    return <div {...props}></div>
  }
```
```
    const newChildren = ReactChildren.map(
      children,
      (child: ReactElement<AccordionContextMenuItemProps>) => {
        if (!child) return null
        return (
          <Menu.Item
            onClick={() => child.props.doChange()}
            style={{ backgroundColor: 'red' }}
          >
            <Icon data={child.props.icon} color="blue" />
            <Typography
              group="navigation"
              variant="menu_title"
              as="span"
              color="blue"
            >
              {child.props.label}
            </Typography>
          </Menu.Item>
        )
      },
    )
```

**Comment by oddvernes** [comment] 2022-11-25 13:19
Closing as it is not a bug on our end. See comment above for solution

**Closed by oddvernes** 2022-11-25 13:19 UTC
Labels: 🐛 bug

**Comment by ingeridhellen** [comment] 2023-09-20 11:41
Could we reopen this? I just had the same issue and this closed issue seems to be the only documentation of it.

**Comment by oddvernes** [comment] 2023-09-20 13:19
Well closed issues don't get deleted and are searchable so a great way to see if a problem has been discussed before🙂. Or did want us to do something specific reagarding this?
