### ISSUE TITLE
Power BI: provide more examples

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1021] opened 2021-01-13 08:00 UTC
As a user I would like to have more Power BI examples of visuals added so that I can use this as a reference when creating my visuals. 

Add more examples for different kinds of visuals and different scenarios/use cases. 

Also requested ( I think from Fusion) to add some more header examples for different scenarios.

**Comment by BirteThornquist** [comment] 2023-03-16 12:24
Duplicate of issue #1024. Closing this issue.

**Closed by BirteThornquist** 2023-03-16 12:24 UTC
Labels: 💡 feature request, powerbi
