### ISSUE TITLE
Conform on "Actions" sub-component

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1199] opened 2021-04-06 06:49 UTC
Determine usage and behaviour of "Actions" sub-components in our components. It looks to mostly be spacing and placements of actions (icons, buttons, etc)

Components with actions so far:
* Dialog
* Card
* Popover
* Banner
* .... more?

**Comment by vnys** [comment] 2022-02-16 08:57
@laliq Is this a duplicate of the work you did with a while ago?

**Comment by akvam** [comment] 2022-09-21 11:27
Somebody that know if this is still relevant? @mimarz , @martalalik

**Comment by martalalik** [comment] 2022-09-21 11:41
I'm closing this issue this is a duplication, just like @vnys mentioned.

**Comment by mimarz** [comment] 2022-09-21 11:58
Well, some work has been done and some still remains, might be good for a newcomer issue or hacktober?

This is similar to work done with #1812 and #2336

**Comment by mimarz** [comment] 2022-09-21 12:20
> Convert to an epic?

Maybe do that evaluation when we move this out of the backlog. We have quite a few epics now already... 🤔

**Comment by oddvernes** [comment] 2023-11-16 13:01
This will implicitly be fully resolved when we implement eds 2.0 tokens

**Closed by oddvernes** 2023-11-16 13:01 UTC
Labels: core-react
