### ISSUE TITLE
Text field document in storefront has some issues

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#2205] opened 2022-05-16 09:20 UTC
Reported in May 2022 gathering 

	- Rebecca/Lucas look at some zeroheight things: 
		○ When inspecting in Figma the text is over top of each other. Also very small and blurry: 
		○ https://eds.equinor.com/0b0c666ab/p/77e7d5-text-field/b/86826a/i/43041814
https://eds.equinor.com/0b0c666ab/p/77e7d5-text-field/b/86826a

		○ ![image.png](https://images.zenhubusercontent.com/6075453285eb60bb55b90568/59159ddd-b889-4967-953e-53bdb21cb969)
		○ So small, blurry, can we fix: https://eds.equinor.com/0b0c666ab/p/31ae8d-select/b/86826a

**Comment by mimarz** [comment] 2022-05-16 09:25
This might be a duplicate or related to #2142 @BeckyBrekke ?

**Comment by mimarz** [comment] 2022-05-18 10:20
Closed as duplicate of #2142

**Closed by mimarz** 2022-05-18 10:20 UTC
Labels: 🐛 bug, storefront
