### ISSUE TITLE
Power BI: Colors for more than 5 categories

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1019] opened 2021-01-13 07:49 UTC
As a user a want to have available a suggestions of colors for when I have more than 5 categories so that I can be consistent and not choose my own. 
As a user a want to have more colors added to the json file, so that when I have a chart with many categories, than brand colors are automatically used and not some random Power BI colors.  (currently only the 8 in the color picker are in the json)

Today we have suggested colors up to 5 categories. Should have examples here. Many charts can be down differently if there are so many categories/bars/lines to be displayed that need to have separate colors. Might be better with separating into smaller charts (small multiples/trellis) for example.

**Comment by BirteThornquist** [comment] 2023-03-16 12:23
This is a duplicate of #2475 . Closing this issue.

**Closed by BirteThornquist** 2023-03-16 12:23 UTC
Labels: 💡 feature request, powerbi
