### ISSUE TITLE
Autocomplete 'option' parameter becomes 'undefined' in 'optionDisabled' callback

### ISSUE THREAD

**Issue by AndreasPresthammer** [equinor/design-system#3677] opened 2024-11-12 11:05 UTC
**Describe the bug**

The `optionDisabled` callback will be called with the 'option' argument as `undefined` when the option is removed from the available `options`.

The type definition of the `optionDisabled` function suggest that the `option` argument will not be undefined, but always contain the actual `option` to  evaluate. This easily (caused a bug for us) will cause an error where we access the `option` argument as if it's there (it can be undefined).

**Steps to reproduce the bug**

https://codesandbox.io/p/sandbox/react-18-playground-forked-dts5gr

**Expected behavior**

It should only call `optionDisabled` with actual options, and never  `undefined`.

**Specifications**

- Version: "@equinor/eds-core-react": "^0.42.2
- Browser: Chrome Version 130.0.6723.116 (Official Build) (64-bit)
- OS: Windows 11

**Comment by oddvernes** [comment] 2024-11-13 14:12
I don't think I fully understand how to reproduce this, could you provide some more information? 
This attempt is presumably not what you were thinking of?
```
export const Multiple: StoryFn<AutocompleteProps<MyOptionType>> = (args) => {
  //const { options } = args
  const [options, setOptions] = useState(stocks)

  const del = () => {
    setOptions((prev) => prev.filter((option) => option.symbol !== 'MSFT'))
  }
  const add = () => {
    setOptions((prev) => [
      ...prev,
      {
        label: 'Microsoft Corporation',
        symbol: 'MSFT',
        trend: '📉',
      },
    ])
  }

  return (
    <>
      <Button onClick={del}>Remove options</Button>
      <Button onClick={add}>add options</Button>
      <Autocomplete
        label="Select multiple stocks"
        options={options}
        multiple
        optionLabel={optionLabel}
        optionDisabled={(item) => {
          console.log(item)
          return item.symbol === 'MSFT'
        }}
      />
    </>
  )
}

**Comment by AndreasPresthammer** [comment] 2024-11-15 13:33
Sorry for the poor explanation and lack of repro.

Here is a repro that I managed to do: https://codesandbox.io/p/sandbox/react-18-playground-forked-dts5gr

Click the 'Clear options' button to make it go 💥

**Comment by oddvernes** [comment] 2024-11-20 09:00
Thanks, so it was specifically singleselect and updating `selectedOptions` (component is in controlled mode) that triggers it. I was able to identify what happens and it seems to be in `downshift`, as their hook returns an array with `null` instead of an empty array  when you send in `setSelectedOptions([])`. I have pushed a fix that will be included in the next release 👍

**Closed** 2024-11-20 11:43 UTC
Labels: 🐛 bug
