### ISSUE TITLE
Create/update documentation for Menu

### ISSUE THREAD

**Issue by sudoole** [equinor/design-system#543] opened 2020-09-07 12:14 UTC
**Documentation Is:**

- [ ] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not Sure?

**Please Explain in Detail**

I used some time to get the Menu item working, and i think some clarifications in the example code would be helpful. 

For me it is not clear from the example which components we need to get the `Menu` component working. It is referred to `Anchor` and `Grid`, which seems to be components defined somewhere, and only used for this example. I actually tried to import the `Anchor` component because i was not sure if I needed it or not :P

None of the imports are shown in the example story, and I had to try some different variants to get it working. From other examples (e.g Table), you first have to import the "main" component, and then destructure it to get the sub component. This is needed for the `MenuItem` component, but I did not see it in the code sample for this component.

**Your Proposal for Changes**

I propose to show all imports needed to get the sample working. If the implementations of the sample components like `Anchor` is very simple, maybe this also could be shown.

**Comment by mimarz** [comment] 2020-09-08 07:00
Hi @sudoole !

Sorry for the lack of documentation, hopefully we'll get developer documentation done on https://eds.equinor.com/components/menu soon ™️🙈

I understand your confusion. Looking at the storybook it only shows the story. Its a big story trying to map out all the different use-cases, and `Anchor` and `Grid` you mention are just helper elements in that story. The `Menu` component can be anchored to any dom element and `Grid` is just a div with some css-grid for that individual story.

You are correct on destructering the `Menu` for the "compound" components (as we call them), `MenuItem` & `MenuSection`.

TDLR; Short code example for getting started with `Menu` anchored to a button: 

```jsx
import { Menu, Button } from '@equinor/eds-core-react'

const { MenuItem, MenuSection } = Menu

const App = () => {
  const [state, setState] = React.useState({
    buttonEl: null,
  })

  const { buttonEl } = state
  const isOpen = Boolean(buttonEl)

  const openMenu = (e) => {
    setState({ ...state, buttonEl: e.target })
  }

  const closeMenu = () => {
    setState({ ...state, buttonEl: null })
  }

  return (
    <>
      <Button
        variant="ghost_icon"
        id="menuButton"
        aria-controls="menu-on-button"
        aria-haspopup="true"
        aria-expanded={isOpen}
        onClick={(e) => (isOpen ? closeMenu() : openMenu(e))}
      >
        Click to open menu
      </Button>
      <Menu
        id="menu-on-button"
        aria-labelledby="menuButton"
        open={isOpen}
        // This can be any dom element. Menu/Popover positions accordingly
        anchorEl={buttonEl}
        // Called when a menuItem is clicked
        onClose={closeMenu}
      >
        <MenuItem> 
          Menu Item 1
        </MenuItem>
        <MenuSection title="Section title">
          <MenuItem>
            Menu Item 2 inside a section
          </MenuItem>
        </MenuSection>
      </Menu>
    </>
  )
}

```


![image](https://user-images.githubusercontent.com/1070981/92443198-72750b00-f1b1-11ea-9ccc-29913fd1012e.png)

**Comment by sudoole** [comment] 2020-09-08 07:49
Thank you @mimarz for a good answer. The example you show, or something similar, would be very helpful to have in the docs :) I was not sure if the available Menu docs was considered finished or not since it kinda looked like the docs for some of the other components. 

I guess I could have asked a question in issue #450 instead of raising a new issue.

**Comment by mimarz** [comment] 2020-09-08 08:55
No worries :) A small heads up, I found a small bug that will be fixed soon :) ([#544](https://github.com/equinor/design-system/issues/544))

**Comment by mimarz** [comment] 2020-09-11 05:56
duplicate of #450

**Comment by mimarz** [comment] 2020-09-11 05:57
duplicate #450

**Closed by mimarz** 2020-09-11 05:57 UTC
Labels: documentation

**Comment by mimarz** [comment] 2020-09-11 05:58
Duplicate of #450
