### ISSUE TITLE
Clear autocomplete input on blur when no option is selected

### ISSUE THREAD

**Issue by FredrikMWold** [equinor/design-system#3207] opened 2024-01-05 11:44 UTC
**Is your feature request related to a problem? Please describe.**

We have had issues where users don't click an option when using the Autocomplete component. The way it is now there is not a distinct enough indicator that tells the user they have not selected a value just typed it in.  As an example we have a form were a lot of the options are short `["A1", "A2", "B3"]` in this case users sometime just type "A1" and move on to the next field. Think they have input the correct value.

**Describe the solution you'd like**

When a user types into the Autocomplete and does not pick an options the input field should clear on blur.

**Describe alternatives you've considered**

Adding a visual indicator that the users has typed something, but not picked anything. That would still require a change to Autocomplete or creating custom styling in every project that overrides the default styling.

**Comment by oddvernes** [comment] 2024-01-12 14:15
Duplicate of #3070 
This issue was discussed on slack last year and we concluded to clear input on blur and add a "no options" item in the dropdown when there are no filter results

**Closed** 2024-01-12 15:06 UTC
Labels: 💡 feature request
