### ISSUE TITLE
Helper text of Autocomplete not showing up

### ISSUE THREAD

**Issue by marclistemann** [equinor/design-system#3153] opened 2023-11-22 13:05 UTC
**Describe the bug**

I was trying to use the new feature of 0.34.0 to add a `helperText `prop to `<Autocomplete>`, however without success. It is just not showing up. The new variant prop works well, though. 

**Steps to reproduce the bug**

1. Create an `<Autocomplete>` element.
2. Add a helper text property, such as `helperText="test"`.

**Specifications**

- Version: 0.34.0
- Browser: Edge Version 119.0.2151.58 (Official build) (64-bit)
- OS: Win10

**Comment by oddvernes** [comment] 2023-11-23 10:19
Hello! I am unable to reproduce this, as helperText works fine in my own test-app. Could you perhaps provide a screenshot of the code, and also inspect the autocomplete element if the helpertext is renderet in dom like this or not:


![Image](https://github.com/equinor/design-system/assets/4499531/fdca77aa-3f00-403f-9cda-589edff5d8aa)

**Comment by marclistemann** [comment] 2023-11-23 12:17
Ok, I don't know what happened, but it suddenly works. Just merged my feature branch (where the issue occurred) into main and voilá. 
Think you can close this issue. Sorry for bothering. Thanks for the feature, btw ;-)

**Comment by oddvernes** [comment] 2023-11-23 14:52
Alright that was strange since `variant` worked at the same time, but i guess unless someone else come along with the samme issue then it was just a ghost in the machine 🤷‍♂ 😅  Closing as resolved

**Closed by oddvernes** 2023-11-23 14:52 UTC
Labels: 🐛 bug
