### ISSUE TITLE
Jest is bundled with eds-core-react

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1406] opened 2021-06-04 09:41 UTC
Jest is bundled with eds-core-react. It uses process.env, with the result that the components don’t work with Webpack 5.

**Comment by mimarz** [comment] 2021-07-15 11:04
This might be fixed in react-testing-library, https://github.com/testing-library/react-testing-library/commit/8a1c8e9396aa7f4843b54e31e2c95404ab8ad940

**Closed** 2021-07-16 10:51 UTC
Labels: 🐛 bug

**Comment by mimarz** [comment] 2021-07-16 13:05
The cause for this was that we had a custom test renderer we used for testing menu, popover etc that was under utils. This meant that the whole `react-testing-library` was bundled along since it was imported by this custom test renderer.
