### ISSUE TITLE
Acknowledge all contributions to the EDS

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#513] opened 2020-08-25 07:46 UTC
We have people who have contributed to the EDS by other means than writing code. To acknowledge all these contributions, we should add them to an “all contributors” section in the README. 

Documentation for how to do that is at https://allcontributors.org/

**Comment by wenche** [comment] 2021-01-12 11:52
Duplicate of #142

**Closed by wenche** 2021-01-12 11:52 UTC
Labels: Low Priority
