### ISSUE TITLE
Improve Tooltip on disabled elements for Safari

### ISSUE THREAD

**Issue by pomfrida** [equinor/design-system#1204] opened 2021-04-08 10:37 UTC
Currently users have to wrap the disabled element with a span (or inline-block element), and add `style={{ pointerEvents: none }} `to the disabled button

Should try to implement this logic to tooltip so the users won't have to do this

**Comment by oddvernes** [comment] 2022-04-26 13:23
The problem is safari fires mouseenter on disabled elements, but not mouseleave, so the tooltip is stuck visible (pressing escape to close it still works). This has been an issue in react [since 2015](https://github.com/facebook/react/issues/4251)
I see reachUi have made [their own workaround](https://github.com/reach/reach-ui/blob/3f50109c2eaf215c5b044171aac537f29d646d17/packages/tooltip/src/index.tsx#L657) using mousemove, but I don't know if this could be easily implemented in our own solution.

**Comment by oddvernes** [comment] 2022-10-21 09:51
Closing as it is both a bug in safari, and `floating-ui` disallows tooltip on disabled buttons entirely now

**Closed by oddvernes** 2022-10-21 09:51 UTC
Labels: core-react, good first issue
