### ISSUE TITLE
As a Product Owner I need the target scope of EDS table component to be defined, so this can guide good solutions when creating the component in React

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#653] opened 2020-10-07 08:49 UTC
Define the scope that our EDS react component (or an external component styled by us) will cover. 

The EDS Core team should setup a suggestion of the scope, and then involve PO to take decisions. 

Examples in Figma illustrating the scope is included in this US if it doesn't already exists. 

Related to #983

**Comment by mimarz** [comment] 2020-11-04 10:54
@equinor/design-system 
Still relevant? or duplicate of #297

**Comment by mimarz** [comment] 2021-01-05 13:02
Started working on a list in this discussion #990

**Comment by lucasveil** [comment] 2021-01-13 17:51
Can you have a [check](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=1048%3A63537) @BirteThornquist

**Closed** 2021-01-27 08:12 UTC
Labels: design, figma
