### ISSUE TITLE
Guidelines for Date picker react component

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#476] opened 2020-08-04 09:33 UTC
EDS will not implement an Data picker component.  This US covers to find a suggestion for how teams using EDS can use Date picker in their solution in the best way. It might be a tradeoff between EDS styling and getting an accessible component.

**Comment by mimarz** [comment] 2020-11-04 10:37
duplicate of #445

**Closed by mimarz** 2020-11-04 10:37 UTC
Labels: documentation, react
